version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/service"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "/gpcc-mocks"
    schedule:
      interval: "weekly"
