server:
  port: ${GPC_CONSUMER_SERVER_PORT:8080}

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: ERROR

spring:
  application:
    name: adaptor-gpc-consumer-test
  cloud:
    gateway:
      routes:
        - id: get-structured-record
          uri: http://localhost:8210
          predicates:
          - Path=/{odsCode}/STU3/1/gpconnect/fhir/Patient/$gpc.getstructuredrecord
          - Method=POST
        - id: get-document
          uri: http://localhost:8210
          predicates:
          - Path=/{odsCode}/STU3/1/gpconnect/documents/Binary/{documentId}
          - Method=GET
        - id: find-a-patient
          uri: http://localhost:8210
          predicates:
          - Path=/{odsCode}/STU3/1/gpconnect/documents/Patient
          - Method=GET

management:
  endpoints:
    web:
      base-path: /
      path-mapping.health: healthcheck
      exposure:
        include: info, health, metrics

gpc-consumer:
  gpc:
    clientCert:
    clientKey:
    rootCA:
    subCA:
  sds:
    url: http://localhost:8210/
    apiKey: test-api-key