server:
  port: ${GPC_CONSUMER_SERVER_PORT:8080}

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: ERROR

management:
  endpoints:
    web:
      base-path: /
      path-mapping.health: healthcheck
      exposure:
        include: info, health, metrics

gpc-consumer:
  gpc:
    clientCert: ${GPC_CONSUMER_SPINE_CLIENT_CERT:}
    clientKey: ${GPC_CONSUMER_SPINE_CLIENT_KEY:}
    rootCA: ${GPC_CONSUMER_SPINE_ROOT_CA_CERT:}
    subCA: ${GPC_CONSUMER_SPINE_SUB_CA_CERT:}
    gpcConsumerUrl: ${GPC_CONSUMER_URL:http://localhost:8080}
    gpcUrl: ${GPC_CONSUMER_GPC_GET_URL:http://localhost:8210}
    findSearchDocumentsPath: ${GPC_CONSUMER_SEARCH_DOCUMENTS_PATH:/B82617/STU3/1/gpconnect/fhir/Patient/**}
    structuredPath: ${GPC_CONSUMER_GPC_STRUCTURED_PATH:/GP0001/STU3/1/gpconnect/fhir/Patient/$gpc.getstructuredrecord}
    findPatientPath: ${GPC_CONSUMER_GPC_GET_PATIENT_PATH:/GP0001/STU3/1/gpconnect/fhir/Patient}
    documentPath: ${GPC_CONSUMER_GPC_GET_DOCUMENT_PATH:/GP0001/STU3/1/gpconnect/documents/fhir/Binary/**}
  sds:
    url: ${GPC_CONSUMER_SDS_URL:http://localhost:8110/}
    apiKey: ${GPC_CONSUMER_SDS_APIKEY}