server:
  port: ${GPC_CONSUMER_SERVER_PORT:8080}

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: ERROR

spring:
  application:
    name: adaptor-gpc-consumer-test
  cloud:
    gateway:
      routes:
        - id: get-structured-record
          uri: ${GPC_CONSUMER_GPC_GET_URL:http://localhost:8210}
          predicates:
          - Path=${GPC_CONSUMER_GPC_STRUCTURED_PATH:/GP0001/STU3/1/gpconnect/fhir/Patient/$gpc.getstructuredrecord}
          - Method=POST

        - id: search-patients-documents
          uri: ${GPC_CONSUMER_GPC_GET_URL:http://localhost:8110}
          predicates:
            - Path=${GP2GP_GPC_GET_PATIENT_ENDPOINT:/GP0001/STU3/1/gpconnect/fhir/Patient/**}
            - Method=GET
          filters:
            - name: ReplaceDocUrl
              args:
                baseMessage: "Search for a patient's documents: "
                gpcConsumerurl: ${GPC_CONSUMER_URL:http://localhost:8080}
                targetUrl: ${GPC_CONSUMER_GPC_GET_URL:http://localhost:8110}

management:
  endpoints:
    web:
      base-path: /
      path-mapping.health: healthcheck
      exposure:
        include: info, health, metrics

gpc-consumer:
  gpc:
    clientCert: ${GPC_CONSUMER_SPINE_CLIENT_CERT:}
    clientKey: ${GPC_CONSUMER_SPINE_CLIENT_KEY:}
    rootCA: ${GPC_CONSUMER_SPINE_ROOT_CA_CERT:}
    subCA: ${GPC_CONSUMER_SPINE_SUB_CA_CERT:}
  sds:
    url: ${GPC_CONSUMER_SDS_URL:http://localhost:8110/}
    apiKey: ${GPC_CONSUMER_SDS_APIKEY}