version: '3.4'

services: 
    gpc-consumer:
      image: ${GPC_CONSUMER_IMAGE:-local/gpc-consumer:latest}
      build:
          context: ../
          dockerfile: docker/service/Dockerfile
      ports: 
        - "8080:8080"
      environment: 
        - GPC_CONSUMER_SERVER_PORT
        - GPC_CONSUMER_ROOT_LOGGING_LEVEL
        - GPC_CONSUMER_LOGGING_LEVEL
        - GPC_CONSUMER_LOGGING_FORMAT
        - GPC_CONSUMER_GPC_GET_URL
        - GPC_CONSUMER_GPC_STRUCTURED_PATH
        - GP2GP_SPINE_CLIENT_CERT
        - GP2GP_SPINE_CLIENT_KEY
        - GP2GP_SPINE_ROOT_CA_CERT
        - GP2GP_SPINE_SUB_CA_CERT
        - GP2GP_SDS_URL
        - GP2GP_SDS_APIKEY