version: '3.4'

services: 
  gpc-consumer:
    image: ${GPC_CONSUMER_IMAGE:-local/gpc-consumer:latest}
    networks:
      - commonforgpc
    build:
        context: ../
        dockerfile: docker/service/Dockerfile
    ports:
      - "8090:8090"
    environment:
      - GPC_CONSUMER_SERVER_PORT
      - GPC_CONSUMER_ROOT_LOGGING_LEVEL
      - GPC_CONSUMER_LOGGING_LEVEL
      - GPC_CONSUMER_LOGGING_FORMAT
      - GPC_CONSUMER_GPC_STRUCTURED_PATH
      - GPC_CONSUMER_GPC_GET_DOCUMENT_PATH
      - GPC_CONSUMER_SPINE_CLIENT_CERT
      - GPC_CONSUMER_SPINE_CLIENT_KEY
      - GPC_CONSUMER_SPINE_ROOT_CA_CERT
      - GPC_CONSUMER_SPINE_SUB_CA_CERT
      - GPC_CONSUMER_SDS_URL
      - GPC_CONSUMER_SDS_APIKEY
      - GPC_CONSUMER_SSP_URL

  gpcc-mocks:
    networks:
      - commonforgpc
    build:
      context: ../
      dockerfile: docker/gpcc-mocks/Dockerfile
    ports:
      - "8110:8080"
      
  gpconnect-db:
    image: mariadb
    networks: 
      - commonforgpc
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=gpconnectdbuser
      - MYSQL_PASSWORD=gpc0nn3ct
      - MYSQL_DATABASE=gpconnect1_5
    command: [
        '--wait_timeout=28800',
    ]

  gpconnect-api:
    image: nhsdigitalmait/gpconnect:1.5.1
    restart : always
    ports:
        - 5000:19191
    networks: 
      - commonforgpc
    environment:
      - TZ=Europe/London
      - DATABASE_ADDRESS=gpconnect-db
      - DATABASE_USERNAME=gpconnectdbuser
      - DATABASE_PASSWORD=gpc0nn3ct
      - DATABASE_SCHEMA=gpconnect1_5
      - SERVER_BASE_URL=https://data.developer.nhs.uk/B82617/STU3/1/gpconnect/fhir
      - CONTEXT_PATH=/B82617/STU3/1/gpconnect/
    links:
      - gpconnect-db
    depends_on:
      - gpconnect-db
   
  tkw:
    image: nhsdigitalmait/tkw_gpconnect_simulator:1.5.1
    restart : always
    ports:
        - 4854:4854
    networks: 
      - commonforgpc
    environment:
      - TZ=Europe/London
    links:
      - gpconnect-api
    depends_on:
      - gpconnect-api


  gpcc-nginx:
    networks:
      - commonforgpc
    depends_on:
      - gpc-consumer
    build:
      context: ./nginx
    ports:
      - "8091:443"

networks:
  commonforgpc:
    external: true
