version: '3.4'

services: 
    gpc-consumer:
      image: ${GPC_CONSUMER_IMAGE:-local/gpc-consumer:latest}
      build:
          context: ../
          dockerfile: docker/service/Dockerfile
      ports: 
        - "8080:8080"
      environment: 
        - GPC_CONSUMER_SERVER_PORT
        - GPC_CONSUMER_ROOT_LOGGING_LEVEL
        - GPC_CONSUMER_LOGGING_LEVEL
        - GPC_CONSUMER_LOGGING_FORMAT