version: '3.4'

services: 
  gpc-consumer:
    image: ${GPC_CONSUMER_IMAGE:-local/gpc-consumer:latest}
    build:
        context: ../
        dockerfile: docker/service/Dockerfile
    ports:
      - "8090:8090"
    environment:
      - GPC_CONSUMER_SERVER_PORT
      - GPC_CONSUMER_ROOT_LOGGING_LEVEL
      - GPC_CONSUMER_LOGGING_LEVEL
      - GPC_CONSUMER_LOGGING_FORMAT
      - GPC_CONSUMER_OVERRIDE_GPC_PROVIDER_URL
      - GPC_CONSUMER_GPC_STRUCTURED_PATH
      - GPC_CONSUMER_GPC_GET_DOCUMENT_PATH
      - GPC_CONSUMER_SPINE_CLIENT_CERT
      - GPC_CONSUMER_SPINE_CLIENT_KEY
      - GPC_CONSUMER_SPINE_ROOT_CA_CERT
      - GPC_CONSUMER_SPINE_SUB_CA_CERT
      - GPC_CONSUMER_SDS_URL
      - GPC_CONSUMER_SDS_APIKEY
      - GPC_CONSUMER_SSP_URL
      - GPC_ENABLE_SDS
  gpcc-wiremock:
    build: ./wiremock
    ports:
      - "8110:8080"
    command:
      - -global-response-templating
