on:
  push:
    tags: "*"

jobs:
  push_to_dockerhub:
    strategy:
      matrix:
        image:
          - {folder: service, dockerhub_name: nia-gpc-consumer-adaptor}
    uses: NHSDigital/integration-adaptor-actions/.github/workflows/release-adaptor-container-image.yml@main
    with:
        dockerhub_name: ${{matrix.image.dockerhub_name}}
        folder: ${{matrix.image.folder}}

    secrets: inherit
